### ISSUE TITLE
Not able to callback

### ISSUE THREAD

**Issue by yashwatwani** [MaksimEkin/COVID19-Literature-Clustering#6] opened 2020-04-20 12:23 UTC
AttributeError                            Traceback (most recent call last)
<ipython-input-89-0bb285d5fc02> in <module>()
     10 
     11 # WIDGETS
---> 12 slider = Slider(start=0, end=20, value=20, step=1, title="Cluster #",callback=input_callback_1)
     13 keyword = TextInput(title="Search:")
     14 

/home/ds/.local/lib/python3.6/site-packages/bokeh/models/widgets/sliders.py in __init__(self, **kwargs)
     68                 raise ValueError("Slider 'start' and 'end' cannot be equal.")
     69 
---> 70         super().__init__(**kwargs)
     71 
     72     title = String(default="", help="""

/home/ds/.local/lib/python3.6/site-packages/bokeh/model.py in __init__(self, **kwargs)
    232         kwargs.pop("id", None)
    233 
--> 234         super().__init__(**kwargs)
    235         default_theme.apply_to_model(self)
    236 

/home/ds/.local/lib/python3.6/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
    245 
    246         for name, value in properties.items():
--> 247             setattr(self, name, value)
    248 
    249     def __setattr__(self, name, value):

/home/ds/.local/lib/python3.6/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
    280 
    281             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 282                 (name, self.__class__.__name__, text, nice_join(matches)))
    283 
    284     def __str__(self):

AttributeError: unexpected attribute 'callback' to Slider, similar attributes are js_event_callbacks

**Comment by MaksimEkin** [comment] 2020-04-21 02:36
@yashwatwani This looks like a Bokeh versioning problem if you are able to import `from lib.call_backs import input_callback, selected_code` successfully. What version of Bokeh do you have? 

**Check the version of Bokeh:**
```
import bokeh
print(bokeh.__version__)
1.3.4
```

Could you please install the version 1.3.4 and try again.
**If using conda:**
`conda install bokeh=1.3.4`

**If using pip:**
`pip install 'bokeh=1.3.4'`

Please let us know if this fixes the problem.

Edit: Correction on the Bokeh version (not 2.0.1, but 1.3.4)

**Comment by MaksimEkin** [comment] 2020-04-23 00:53
@yashwatwani Can you try Bokeh version 1.3.4?

**Comment by MaksimEkin** [comment] 2020-04-23 21:29
We were able to reproduce the error by upgrading to Bokeh 2.0.1. **Using Bokeh 1.3.4 resolves the error**; therefore, closing the issue.

@SoloNick

**Closed as completed by MaksimEkin** 2020-04-23 21:29 UTC
Labels: good first issue

**Comment by Shruthihanu** [comment] 2020-07-08 07:10
Hi, 

I am new to this forum and python programming.. 

I was trying to run the code in my system, below is the error I get when I run - "from call_backs import input_callback, selected_code"

How do I install call_backs in conda. 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-2c4a5f31eb17> in <module>
----> 1 from call_backs import input_callback, selected_code

ModuleNotFoundError: No module named 'call_backs'

**Comment by MaksimEkin** [comment] 2020-07-08 15:40
Make sure the [lib folder](https://github.com/MaksimEkin/COVID19-Literature-Clustering/tree/master/lib) is in the same directory as the Notebook. Error is complaining about [call_backs.py](https://github.com/MaksimEkin/COVID19-Literature-Clustering/blob/master/lib/call_backs.py).

**Comment by Shruthihanu** [comment] 2020-07-11 12:48
Hi, 

Yes, error is on call_backs.... not sure how to install this module. 

<img width="563" alt="call_backs" src="https://user-images.githubusercontent.com/20811027/87224412-d3938480-c3a2-11ea-8766-2f457429a731.PNG">

can you guide me.

**Comment by SoloNick** [comment] 2020-07-11 16:46
“call_backs” is in lib/call_backs.py. You cannot conda install it.
